; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24210.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Charith\AppData\Local\Temp\.NETFramework,Version=v4.6.2.AssemblyAttributes.cpp"
